import prb1 from "@/src/assets/products/p1.jpg";
import prb2 from "@/src/assets/products/p2.jpg";
import prb3 from "@/src/assets/products/p3.jpg";
import prb4 from "@/src/assets/products/p4.jpg";
import prb5 from "@/src/assets/products/p5.jpg";
import prb6 from "@/src/assets/products/p6.jpg";
import prb7 from "@/src/assets/products/p7.jpg";
import prb8 from "@/src/assets/products/p8.jpg";
import prb9 from "@/src/assets/products/p9.jpg";
import prb10 from "@/src/assets/products/p10.jpg";
import prb11 from "@/src/assets/products/p11.jpg";
import prb12 from "@/src/assets/products/p12.jpg";
import prb13 from "@/src/assets/products/a1.jpg";
import prb14 from "@/src/assets/products/a2.jpg";
import prb15 from "@/src/assets/products/a3.jpg";
import prb16 from "@/src/assets/products/a4.jpg";
import prb17 from "@/src/assets/products/a5.jpg";
import prb18 from "@/src/assets/products/a6.jpg";
import prb19 from "@/src/assets/products/tv1.jpg";
import prb20 from "@/src/assets/products/tv2.jpg";
import prb21 from "@/src/assets/products/tv3.jpg";
import prb22 from "@/src/assets/products/tv4.jpg";
import prb23 from "@/src/assets/products/tv5.jpg";
import prb24 from "@/src/assets/products/tv6.jpg";
import prb25 from "@/src/assets/products/m1.jpg";
import prb26 from "@/src/assets/products/m2.jpg";
import prb27 from "@/src/assets/products/m3.jpg";
import prb28 from "@/src/assets/products/m4.jpg";
import prb29 from "@/src/assets/products/m5.jpg";
import prb30 from "@/src/assets/products/m6.jpg";
import prb31 from "@/src/assets/products/L1.jpg";
import prb32 from "@/src/assets/products/L2.jpg";
import prb33 from "@/src/assets/products/L3.jpg";
import prb34 from "@/src/assets/products/L4.jpg";
import prb35 from "@/src/assets/products/L5.jpg";
import prb36 from "@/src/assets/products/L6.jpg";
import prb37 from "@/src/assets/products/f1.jpg";
import prb38 from "@/src/assets/products/f2.jpg";
import prb39 from "@/src/assets/products/f3.jpg";
import prb40 from "@/src/assets/products/f4.jpg";
import prb41 from "@/src/assets/products/f5.jpg";
import prb42 from "@/src/assets/products/f6.jpg";
import prb43 from "@/src/assets/products/k1.jpg";
import prb44 from "@/src/assets/products/k2.jpg";
import prb45 from "@/src/assets/products/k3.jpg";
import prb46 from "@/src/assets/products/k4.jpg";
import prb47 from "@/src/assets/products/k5.jpg";
import prb48 from "@/src/assets/products/k6.jpg";
import prb49 from "@/src/assets/products/g1.jpg";
import prb50 from "@/src/assets/products/g2.jpg";
import prb51 from "@/src/assets/products/g3.jpg";
import prb52 from "@/src/assets/products/g4.jpg";
import prb53 from "@/src/assets/products/g5.jpg";
import prb54 from "@/src/assets/products/g6.jpg";
import prb55 from "@/src/assets/products/bd1.jpg";
import prb56 from "@/src/assets/products/bd2.jpg";
import prb57 from "@/src/assets/products/bd3.jpg";
import prb58 from "@/src/assets/products/bd4.jpg";
import prb59 from "@/src/assets/products/bd5.jpg";
import prb60 from "@/src/assets/products/bd6.jpg";
import prb61 from "@/src/assets/products/n1.jpg";
import prb62 from "@/src/assets/products/n2.jpg";
import prb63 from "@/src/assets/products/n3.jpg";
import prb64 from "@/src/assets/products/n4.jpg";
import prb65 from "@/src/assets/products/n5.jpg";
import prb66 from "@/src/assets/products/n6.jpg";
import prb67 from "@/src/assets/products/c1.jpg";
import prb68 from "@/src/assets/products/c2.jpg";
import prb69 from "@/src/assets/products/c3.jpg";
import prb70 from "@/src/assets/products/c4.jpg";
import prb71 from "@/src/assets/products/c5.jpg";
import prb72 from "@/src/assets/products/c6.jpg";

export const productList = [
  {
    id: 1,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb1,
  },
  {
    id: 2,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb2,
  },
  {
    id: 3,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb3,
  },
  {
    id: 4,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb4,
  },
  {
    id: 5,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb5,
  },
  {
    id: 6,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb6,
  },
  {
    id: 7,
    title: "Kelvinator 537L Side by Side Glass Door",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 98,
    discount: 70,
    thumbelImage: prb7,
  },
  {
    id: 8,
    title: "Sony Bravia 2 43 Inch LED 4K Smart Google",
    price: 2300,
    mrpPrice: 5000,
    rating: 5,
    selProduct: 198,
    discount: 50,
    thumbelImage: prb8,
  },
  {
    id: 9,
    title: "Samsung 43 Inch Crystal UHD 4K Smart TV",
    price: 6200,
    mrpPrice: 6100,
    rating: 3.5,
    selProduct: 200,
    discount: 10,
    thumbelImage: prb9,
  },
  {
    id: 10,
    title: "Samsung 43 Inch Crystal UHD 4K Smart TV",
    price: 3600,
    mrpPrice: 3200,
    rating: "",
    selProduct: "",
    discount: "",
    thumbelImage: prb10,
  },
  {
    id: 11,
    title: "Samsung 43 Inch Crystal UHD 4K Smart TV",
    price: 7600,
    mrpPrice: 5200,
    rating: 3,
    selProduct: 200,
    discount: 98,
    thumbelImage: prb11,
  },
  {
    id: 12,
    title: "Samsung 43 Inch Crystal UHD 4K Smart TV",
    price: 7600,
    mrpPrice: 5200,
    rating: 3,
    selProduct: 200,
    discount: 98,
    thumbelImage: prb12,
  },
  {
    id: 13,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb13,
  },
  {
    id: 14,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb14,
  },
  {
    id: 15,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb15,
  },
  {
    id: 16,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb16,
  },
  {
    id: 17,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb17,
  },
  {
    id: 18,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb18,
  },
   {
    id: 19,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb19,
  },
  {
    id: 20,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb20,
  },
  {
    id: 21,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb21,
  },
  {
    id: 22,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb22,
  },
  {
    id: 23,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb23,
  },
  {
    id: 24,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb24,
  },
  {
    id: 25,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb25,
  },
  {
    id: 26,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb26,
  },
  {
    id: 27,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb27,
  },
  {
    id: 28,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb28,
  },
  {
    id: 29,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb29,
  },
  {
    id: 30,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb30,
  },
  {
    id: 31,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb31,
  },
  {
    id: 32,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb32,
  },
  {
    id: 33,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb33,
  },
  {
    id: 34,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb34,
  },
  {
    id: 35,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb35,
  },
  {
    id: 36,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb36,
  },
  {
    id: 37,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb37,
  },
  {
    id: 38,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb38,
  },
  {
    id: 39,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb39,
  },
  {
    id: 40,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb40,
  },
  {
    id: 41,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb41,
  },
  {
    id: 42,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb42,
  },
  {
    id: 43,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb43,
  },
  {
    id: 44,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb44,
  },
  {
    id: 45,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb45,
  },
  {
    id: 46,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb46,
  },
  {
    id: 47,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb47,
  },
  {
    id: 48,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb48,
  },
  {
    id: 49,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb49,
  },
  {
    id: 50,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb50,
  },
  {
    id: 51,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb51,
  },
  {
    id: 52,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb52,
  },
  {
    id: 53,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb53,
  },
  {
    id: 54,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb54,
  },
  {
    id: 55,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb55,
  },
  {
    id: 56,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb56,
  },
  {
    id: 57,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb57,
  },
  {
    id: 58,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb58,
  },
  {
    id: 59,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb59,
  },
  {
    id: 60,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb60,
  },

   {
    id: 61,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb61,
  },
  {
    id: 62,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb62,
  },
  {
    id: 63,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb63,
  },
  {
    id: 64,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb64,
  },
  {
    id: 65,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb65,
  },
  {
    id: 66,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb66,
  },
  {
    id: 67,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb67,
  },
  {
    id: 68,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb68,
  },
  {
    id: 69,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb69,
  },
  {
    id: 70,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb70,
  },
  {
    id: 71,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb71,
  },
  {
    id: 72,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb72,
  },
];
