import prb1 from "@/src/assets/products/p1.jpg";
import prb2 from "@/src/assets/products/p2.jpg";
import prb3 from "@/src/assets/products/p3.jpg";
import prb4 from "@/src/assets/products/p4.jpg";
import prb5 from "@/src/assets/products/p5.jpg";
import prb6 from "@/src/assets/products/p6.jpg";
import prb7 from "@/src/assets/products/p7.jpg";
import prb8 from "@/src/assets/products/p8.jpg";
import prb9 from "@/src/assets/products/p9.jpg";
import prb10 from "@/src/assets/products/p10.jpg";
import prb11 from "@/src/assets/products/p11.jpg";
import prb12 from "@/src/assets/products/p12.jpg";

export const productList = [
  {
    id: 1,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb1,
  },
  {
    id: 2,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb2,
  },
  {
    id: 3,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb3,
  },
  {
    id: 4,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb4,
  },
  {
    id: 5,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb5,
  },
  {
    id: 6,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb6,
  },
  {
    id: 7,
    title: "Kelvinator 537L Side by Side Glass Door",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 98,
    discount: 70,
    thumbelImage: prb7,
  },
  {
    id: 8,
    title: "Sony Bravia 2 43 Inch LED 4K Smart Google",
    price: 2300,
    mrpPrice: 5000,
    rating: 5,
    selProduct: 198,
    discount: 50,
    thumbelImage: prb8,
  },
  {
    id: 9,
    title: "Samsung 43 Inch Crystal UHD 4K Smart TV",
    price: 6200,
    mrpPrice: 6100,
    rating: 3.5,
    selProduct: 200,
    discount: 10,
    thumbelImage: prb9,
  },
  {
    id: 10,
    title: "Samsung 43 Inch Crystal UHD 4K Smart TV",
    price: 3600,
    mrpPrice: 3200,
    rating: "",
    selProduct: "",
    discount: "",
    thumbelImage: prb10,
  },
  {
    id: 11,
    title: "Samsung 43 Inch Crystal UHD 4K Smart TV",
    price: 7600,
    mrpPrice: 5200,
    rating: 3,
    selProduct: 200,
    discount: 98,
    thumbelImage: prb11,
  },
  {
    id: 12,
    title: "Samsung 43 Inch Crystal UHD 4K Smart TV",
    price: 7600,
    mrpPrice: 5200,
    rating: 3,
    selProduct: 200,
    discount: 98,
    thumbelImage: prb12,
  },
  {
    id: 13,
    title: "Haier 1.5 Ton ZenGlow Inverter Air Conditioner",
    price: 3500,
    mrpPrice: 4201,
    rating: 4.5,
    selProduct: 120,
    discount: 17,
    thumbelImage: prb1,
  },
  {
    id: 14,
    title:
      "Walton 1.5 Ton Riverine Prime Intelligent Inverter Air",
    price: 2800,
    mrpPrice: 3201,
    rating: 5,
    selProduct: 100,
    discount: 12,
    thumbelImage: prb2,
  },
  {
    id: 15,
    title: "Midea 1.5 Ton Flash Cool Inverter Air",
    price: 1600,
    mrpPrice: 2000,
    rating: 3,
    selProduct: 150,
    discount: 20,
    thumbelImage: prb3,
  },
  {
    id: 16,
    title: "Haier 8Kg Top Load Automatic Washing)",
    price: 4200,
    mrpPrice: 5000,
    rating: 4,
    selProduct: 70,
    discount: 16,
    thumbelImage: prb4,
  },
  {
    id: 17,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb5,
  },
  {
    id: 18,
    title: "OnePlus Nord CE5 5G 8GB/256GB (Blue Tide)",
    price: 6500,
    mrpPrice: 7000,
    rating: 4.5,
    selProduct: 125,
    discount: 70,
    thumbelImage: prb6,
  },
];
